# Generated by Django 3.2 on 2021-06-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.IntegerField()),
                ('barcode', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PickingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('totalSteps', models.IntegerField()),
                ('currentStep', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
                ('pickcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picking.pickcart')),
            ],
        ),
        migrations.CreateModel(
            name='PickingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepNo', models.IntegerField()),
                ('pickingLocation', models.IntegerField()),
                ('pickCartSection', models.IntegerField()),
                ('productName', models.CharField(max_length=100)),
                ('totalQuantity', models.FloatField()),
                ('pickedQuantity', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('pickingSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picking.pickingsession')),
            ],
        ),
    ]
