# Generated by Django 3.2 on 2021-06-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0003_pickcartsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickcart',
            name='section',
        ),
    ]
