apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-access-log-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/backendAccessLog"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-access-log-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi