apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataflow
spec:
  selector:
    matchLabels:
      app: dataflow
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dataflow
    spec:
      containers:
      - image: docker.pkg.github.com/emrelg/wms-dataflow/dataflow:dev
        imagePullPolicy: Always
        name: dataflow
        env:
          - name: TZ
            value: Europe/Zurich
        volumeMounts:
          - mountPath: "/home/app/invoices"
            name: invoice-pv
          - mountPath: "/home/app/config"
            name: secret
          - mountPath: "/home/app/dataFlowLogs"
            name: dataflow-logs-pv
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      volumes:
        - name: invoice-pv
          persistentVolumeClaim:
            claimName: invoice-pv-claim
        - name: secret
          secret:
            secretName: dataflow-secret
        - name: dataflow-logs-pv
          persistentVolumeClaim:
            claimName: dataflow-logs-pvc