apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.10
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/etc/nginx"
            name: nginx-pv
          - mountPath: "/media"
            name: invoice-pv
      volumes:
        - name: nginx-pv
          persistentVolumeClaim:
            claimName: nginx-pvc
        - name: invoice-pv
          persistentVolumeClaim:
            claimName: invoice-pv-claim