# Generated by Django 3.2 on 2021-05-27 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_auto_20210505_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permisson',
            new_name='Permission',
        ),
        migrations.RenameModel(
            old_name='UserPermisson',
            new_name='UserPermission',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='permisson',
            new_name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='permissons',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permissions',
            field=models.ManyToManyField(to='authentication.Permission'),
        ),
    ]
