# Generated by Django 3.2 on 2021-04-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=50)),
                ('lastupdate', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('cycleTime', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('db', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.IntegerField()),
                ('cacheId', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=1500)),
                ('result', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.IntegerField()),
                ('cacheId', models.IntegerField()),
                ('remoteId', models.CharField(default='', max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='odoo12_staging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleOrder', models.CharField(max_length=4000)),
                ('stockPicking', models.CharField(max_length=4000)),
                ('stockMove', models.CharField(max_length=4000)),
                ('productProduct', models.CharField(max_length=4000)),
                ('resPartner', models.CharField(max_length=4000)),
                ('accountInvoice', models.CharField(max_length=4000)),
                ('summary', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.IntegerField()),
                ('cacheId', models.IntegerField()),
                ('remoteId', models.CharField(max_length=50)),
                ('productLines', models.CharField(max_length=1000)),
                ('shippingInformation', models.CharField(max_length=500)),
                ('invoice', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('size', models.CharField(default='', max_length=50)),
                ('commands', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('endpoint_id', 'cacheId', 'remoteId'), name='order-unique-constraint'),
        ),
    ]
