# Generated by Django 3.2 on 2021-05-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataflow',
            name='db',
        ),
        migrations.RemoveField(
            model_name='dataflow',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dataflow',
            name='url',
        ),
        migrations.RemoveField(
            model_name='dataflow',
            name='username',
        ),
    ]
