# Generated by Django 3.2 on 2021-06-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0001_initial'),
        ('dataflow', '0003_remove_dataflow_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickingSession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='picking.pickingsession'),
        ),
    ]
